# This workload will format all .py files with black formatter.

name: Format files

on:
  push:
    branches: ['main']

permissions:
  contents: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install black formatter
      run:
        pip install black --upgrade
    - name: Run black formatter
      run:
        python -m black .
